### ISSUE TITLE
Cannot import name 'ReadTimeout'

### ISSUE THREAD

**Issue by rmichela** [docker/compose#4421]
I get the following error trying to run `docker-compose --version`.

```
rmichela@rmichela-wsl:/usr/lib/python2.7/dist-packages$ docker-compose --version
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 7, in <module>
    from compose.cli.main import main
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 41, in <module>
    from . import errors
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/errors.py", line 12, in <module>
    from requests.exceptions import ReadTimeout
ImportError: cannot import name 'ReadTimeout'
```

`pip freeze` shows the following relevant versions:
```
docker==2.0.2
docker-compose==1.10.1
docker-pycreds==0.2.1
dockerpty==0.4.1
requests==2.13.0
```
I'm running python 3.5.2 on Ubuntu 14.04.
Any ideas?

**Comment by shin-** [comment]
You shouldn't have any problem with that import if you're using requests 2.13.

Is your `pip` command showing packages for your Python 3 installation? What does `pip --version` output? Is `pip3` in your PATH?

**Comment by xataz** [comment]
Hi, same problem after update docker-compose to 1.11.1 on debian jessie (new install) : 
```shell
$ pip --version
pip 1.5.6 from /usr/lib/python2.7/dist-packages (python 2.7)
$ python --version
Python 2.7.9
$ pip freeze
PyYAML==3.11
argparse==1.2.1
backports.ssl-match-hostname==3.5.0.1
cached-property==1.3.0
cffi==0.8.6
chardet==2.3.0
colorama==0.3.2
cryptography==0.6.1
docker==2.0.2
docker-compose==1.11.1
docker-pycreds==0.2.1
dockerpty==0.4.1
docopt==0.6.2
enum34==1.1.6
functools32==3.2.3-2
html5lib==0.999
iotop==0.6
ipaddress==1.0.18
jsonschema==2.6.0
ndg-httpsclient==0.3.2
ply==3.4
pyOpenSSL==0.14
pyasn1==0.1.7
pycparser==2.10
python-apt==0.9.3.12
requests==2.4.3
six==1.8.0
texttable==0.8.7
urllib3==1.9.1
websocket-client==0.40.0
wheel==0.24.0
wsgiref==0.1.2
$ docker-compose version
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 7, in <module>
    from compose.cli.main import main
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 41, in <module>
    from . import errors
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/errors.py", line 14, in <module>
    from requests.packages.urllib3.exceptions import ReadTimeoutError
ImportError: cannot import name ReadTimeoutError
```

**Comment by shin-** [comment]
Your version of requests is too old. Do "pip install -U requests==2.11.1"

**Comment by xataz** [comment]
It's ok for me after update requests.

**Comment by shin-** [comment]
This is probably the same issue as #4425 - closing as the fix for this has been merged and will be in the upcoming 1.11.2
