### ISSUE TITLE
docker-compose not compatible with pip 8.1.1

### ISSUE THREAD

**Issue by jalberto** [docker/compose#4102]
```
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 328, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 748, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 448, in _prepare_file
    req_to_install, finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 387, in _check_skip_installed
    req_to_install.check_if_exists()
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1011, in check_if_exists
    self.req.project_name
AttributeError: 'Requirement' object has no attribute 'project_name'
```

Seems related to: https://github.com/pypa/pip/issues/3687

it does works with pip 8.1.2, but docker documentation says pip 1.6.0 and up are supported.

pip 8.1.1 is default version in ubuntu 16.04 LTS

**Comment by shin-** [comment]
This doesn't seem to be a Compose issue - it's just pip 8.1.1 that's broken. Or am I misunderstanding?

**Comment by jalberto** [comment]
@shin- well it depedns on your definition of broken. If I understand correctly the use of internal PIP API is not supported, so is not broken but a design decision.

Does compose use that internal API?

**Comment by shin-** [comment]
We don't use pip's internal API.

**Comment by j4m3s** [comment]
pip 8.1.1 is the latest version available in Ubuntu 16.04 (the latest LTS version), meaning the pip install of docker-compose doesn't work.

Interestingly it does work fine if you install as your own user (without sudo) - but that doesn't help with building servers that have multiple users of course.
