### ISSUE TITLE
Incompatibility with docker 2.4.2

### ISSUE THREAD

**Issue by lindycoder** [docker/compose#5495]
Hi!

Just wanted to report that docker-compose 1.18 is not compatible with docker 2.4.2 which is now in the openstack-pike upper constraint file, which is the reason i'm on this docker version
 
https://git.openstack.org/cgit/openstack/requirements/plain/upper-constraints.txt?h=stable/pike

Here's my error
```
ERROR: for ....  __init__() got an unexpected keyword argument 'mounts'
Traceback (most recent call last):
  File "/tmp/venv/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/tmp/venv/lib/python2.7/site-packages/compose/cli/main.py", line 71, in main
    command()
  File "/tmp/venv/lib/python2.7/site-packages/compose/cli/main.py", line 124, in perform_command
    handler(command, command_options)
  File "/tmp/venv/lib/python2.7/site-packages/compose/cli/main.py", line 959, in up
    start=not no_start
  File "/tmp/venv/lib/python2.7/site-packages/compose/project.py", line 479, in up
    get_deps,
  File "/tmp/venv/lib/python2.7/site-packages/compose/parallel.py", line 80, in parallel_execute
    raise error_to_reraise
TypeError: __init__() got an unexpected keyword argument 'mounts'
```

Works fine with latest docker (2.6.1)
Works fine with last docker-compose (1.17.1)

Thank you for your great work!

**Comment by lindycoder** [comment]
I've got a better stacktrace here i think

```
     [exec] Traceback (most recent call last):
     [exec]   File "/ws/.tox/integration/bin/docker-compose", line 11, in <module>
     [exec]     sys.exit(main())
     [exec]   File "/ws/.tox/integration/lib/python3.4/site-packages/compose/cli/main.py", line 71, in main
     [exec]     command()
     [exec]   File "/ws/.tox/integration/lib/python3.4/site-packages/compose/cli/main.py", line 124, in perform_command
     [exec]     handler(command, command_options)
     [exec]   File "/ws/.tox/integration/lib/python3.4/site-packages/compose/cli/main.py", line 959, in up
     [exec]     start=not no_start
     [exec]   File "/ws/.tox/integration/lib/python3.4/site-packages/compose/project.py", line 479, in up
     [exec]     get_deps,
     [exec]   File "/ws/.tox/integration/lib/python3.4/site-packages/compose/parallel.py", line 80, in parallel_execute
     [exec]     raise error_to_reraise
     [exec]   File "/ws/.tox/integration/lib/python3.4/site-packages/compose/parallel.py", line 178, in producer
     [exec]     result = func(obj)
     [exec]   File "/ws/.tox/integration/lib/python3.4/site-packages/compose/project.py", line 465, in do
     [exec]     project_services=scaled_services
     [exec]   File "/ws/.tox/integration/lib/python3.4/site-packages/compose/service.py", line 478, in execute_convergence_plan
     [exec]     scale, detached, start, project_services
     [exec]   File "/ws/.tox/integration/lib/python3.4/site-packages/compose/service.py", line 403, in _execute_convergence_create
     [exec]     parent_objects=project_services
     [exec]   File "/ws/.tox/integration/lib/python3.4/site-packages/compose/parallel.py", line 80, in parallel_execute
     [exec]     raise error_to_reraise
     [exec]   File "/ws/.tox/integration/lib/python3.4/site-packages/compose/parallel.py", line 178, in producer
     [exec]     result = func(obj)
     [exec]   File "/ws/.tox/integration/lib/python3.4/site-packages/compose/service.py", line 400, in <lambda>
     [exec]     lambda service_name: create_and_start(self, service_name.number),
     [exec]   File "/ws/.tox/integration/lib/python3.4/site-packages/compose/service.py", line 391, in create_and_start
     [exec]     container = service.create_container(number=n, quiet=True)
     [exec]   File "/ws/.tox/integration/lib/python3.4/site-packages/compose/service.py", line 294, in create_container
     [exec]     previous_container=previous_container,
     [exec]   File "/ws/.tox/integration/lib/python3.4/site-packages/compose/service.py", line 806, in _get_container_create_options
     [exec]     one_off=one_off)
     [exec]   File "/ws/.tox/integration/lib/python3.4/site-packages/compose/service.py", line 920, in _get_container_host_config
     [exec]     mounts=options.get('mounts'),
     [exec]   File "/ws/.tox/integration/lib/python3.4/site-packages/docker/api/container.py", line 605, in create_host_config
     [exec]     return HostConfig(*args, **kwargs)
     [exec] TypeError: __init__() got an unexpected keyword argument 'mounts'
```

**Comment by shin-** [comment]
Yes, Compose 1.18.0 leverages some of the newest additions in docker 2.6. Dependencies are declared accordingly in our `setup.py` and `requirements.txt`. https://github.com/docker/compose/blob/master/setup.py#L39

**Comment by lindycoder** [comment]
right, i'll blame this on pip not warning for conflicts :P Thank you!
