### ISSUE TITLE
AttributeError: 'module' object has no attribute 'OPENSSL_VERSION'

### ISSUE THREAD

**Issue by AndrewSwerlick** [docker/compose#1620]
I'm getting a strange error no matter what command I run with docker-compse. From what I can tell, this suggest that docker-compose is trying to run under python 2.6 as opposed to the bundled 2.7. 

I'm running Centos 6.6 in Digital Ocean. Interestingly docker-compose works on a different Centos 6.6 installation built from a vagrant box, but not on DO. I have replicated this issue with a fresh droplet on digital ocean using the following steps.

1. Create droplet using the Centos 6.5 x64 image
2. Run `yum install epel-release`
3. Run `yum install python-pip`
4. Run `pip install docker-compose`
5. Run `docker-compose --version`

The full error text is below

    Traceback (most recent call last):
      File "/usr/bin/docker-compose", line 9, in <module>
        load_entry_point('docker-compose==1.3.1', 'console_scripts', 'docker-compose')()
      File "/usr/lib/python2.6/site-packages/compose/cli/main.py", line 31, in main
        command.sys_dispatch()
      File "/usr/lib/python2.6/site-packages/compose/cli/docopt_command.py", line 21, in sys_dispatch
        self.dispatch(sys.argv[1:], None)
      File "/usr/lib/python2.6/site-packages/compose/cli/command.py", line 34, in dispatch
        super(Command, self).dispatch(*args, **kwargs)
      File "/usr/lib/python2.6/site-packages/compose/cli/docopt_command.py", line 24, in dispatch
        self.perform_command(*self.parse(argv, global_options))
      File "/usr/lib/python2.6/site-packages/compose/cli/docopt_command.py", line 30, in parse
        options = docopt_full_help(getdoc(self), argv, **self.docopt_options())
      File "/usr/lib/python2.6/site-packages/compose/cli/main.py", line 106, in docopt_options
        options['version'] = get_version_info()
      File "/usr/lib/python2.6/site-packages/compose/cli/utils.py", line 132, in get_version_info
        "OpenSSL version: %s" % ssl.OPENSSL_VERSION,
    AttributeError: 'module' object has no attribute 'OPENSSL_VERSION'

**Comment by galet** [comment]
I have the same problem when upgraded from docker-compose 1.2.0 to 1.3.1. 
OS is RHEL 6.6. Installed from pip into a clean virtualenv.

**Comment by aanand** [comment]
Compose requires Python 2.7. We should make this clear in the docs.

Not sure what you mean by "the bundled 2.7". If you're installing via Pip, Compose does not bundle a Python executable.

If I run your commands in a `centos:6` Docker container I can reproduce the error, but that's not surprising given the installed Python is 2.6:

```
$ docker run -it centos:6 bash
[root@fa3ed9f1a6e1 /]# yum install epel-release
[root@fa3ed9f1a6e1 /]# yum install python-pip
[root@fa3ed9f1a6e1 /]# python --version
Python 2.6.6
```

**Comment by Diaoul** [comment]
https://github.com/docker/compose/blob/master/setup.py#L47-L48
That's surprising for a 2.7+ package.
Also, setting proper classifiers in `setup.py` can help, the pypi page is usually the first one I'm reading before the docs to determine which python version is supported.

**Comment by dnephin** [comment]
We now have proper classifiers for version.
