### PR TITLE
Reinitialize sys.path after it's been potentially modified by pip

### LINKED ISSUE #4425: docker-compose 1.10.1 causes build to fail on 14.04 (module object has no attribute connection)
(Sorry for the rushed bug report, just heading out the door...  will fix later if there's missing details)

Ubuntu 14.04 (on vagrant)
Installing docker on the system, which brings in docker-compose 1.10.1 package

Try to do "docker-compose build", fails:

```
$ docker-compose build
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 7, in <module>
    from compose.cli.main import main
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 41, in <module>
    from . import errors
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/errors.py", line 10, in <module>
    from docker.errors import APIError
  File "/usr/local/lib/python2.7/dist-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/local/lib/python2.7/dist-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 11, in <module>
    from .build import BuildApiMixin
  File "/usr/local/lib/python2.7/dist-packages/docker/api/build.py", line 9, in <module>
    from .. import utils
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/__init__.py", line 2, in <module>
    from .utils import (
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/utils.py", line 19, in <module>
    from .. import tls
  File "/usr/local/lib/python2.7/dist-packages/docker/tls.py", line 5, in <module>
    from .transport import SSLAdapter
  File "/usr/local/lib/python2.7/dist-packages/docker/transport/__init__.py", line 3, in <module>
    from .ssladapter import SSLAdapter
  File "/usr/local/lib/python2.7/dist-packages/docker/transport/ssladapter.py", line 22, in <module>
    urllib3.connection.match_hostname = match_hostname
AttributeError: 'module' object has no attribute 'connection'
```

This is a known issue (https://github.com/docker/docker-py/issues/1054), but was working fine with docker-compose 1.10.0.

But this change in docker-compose 1.10.1 is causing the above error:

https://github.com/docker/compose/commit/5895d8bbc9939524b449e296ac93d8e98aa70eb0#diff-228ac110a2a9f4c594407b860e1b0ed0

Specifically:
```python
pip = __import__('pip')
```
This line alters the sys.path.  Before that line:
```
sys.path: ['/usr/local/bin', '/test', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
```
After that line:
```
sys.path: ['/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl', '/usr/share/python-wheels/urllib3-1.7.1-py2.py3-none-any.whl', '/usr/share/python-wheels/html5lib-0.999-py2.py3-none-any.whl', '/usr/share/python-wheels/pip-1.5.4-py2.py3-none-any.whl', '/usr/share/python-wheels/requests-2.2.1-py2.py3-none-any.whl', '/usr/share/python-wheels/distlib-0.1.8-py2.py3-none-any.whl', '/usr/share/python-wheels/chardet-2.2.1-py2.py3-none-any.whl', '/usr/share/python-wheels/six-1.5.2-py2.py3-none-any.whl', '/usr/share/python-wheels/colorama-0.2.5-py2.py3-none-any.whl', '/usr/local/bin', '/test', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
```
Notably, the "/usr/share/python-wheels/urllib3-1.7.1-py2.py3-none-any.whl" package is added to the top of the path, making it impossible to override with PYTHONPATH or anything else later.  This means request will be forced to use the older ubuntu 14.04's urllib 1.7, which breaks everything.

Downgrading to docker-compose 1.10.0 fixes this, allowing the code to use a newer urllib3 version than what's installed in the system.

### LINKED ISSUE #4483: Exception on 404 when using the HTTP interface directly
Hi guys.

I've been struggling with a weird issue:

```
compose.cli.verbose_proxy.proxy_callable: docker inspect_network <- (u'mytest_default')
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 88, in main
    command()
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 140, in perform_command
    handler(command, command_options)
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 900, in up
    remove_orphans=remove_orphans)
  File "/usr/local/lib/python2.7/dist-packages/compose/project.py", line 387, in up
    self.initialize()
  File "/usr/local/lib/python2.7/dist-packages/compose/project.py", line 431, in initialize
    self.networks.initialize()
  File "/usr/local/lib/python2.7/dist-packages/compose/network.py", line 203, in initialize
    network.ensure()
  File "/usr/local/lib/python2.7/dist-packages/compose/network.py", line 59, in ensure
    data = self.inspect()
  File "/usr/local/lib/python2.7/dist-packages/compose/network.py", line 91, in inspect
    return self.client.inspect_network(self.full_name)
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/verbose_proxy.py", line 55, in proxy_callable
    result = getattr(self.obj, call_name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 35, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/network.py", line 158, in inspect_network
    return self._result(res, json=True)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 216, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 210, in _raise_for_status
    response.raise_for_status()
  File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/models.py", line 840, in raise_for_status
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://docker:2375/v1.25/networks/baseagent_default
```

From the looks of it, the client fails to recover from a 404 (an expected one, the network `mytest_default` doesn't exist yet.

I have been able to create a more self-contained test to reproduce the error (spoiler alert it relies on dind, but that should be irrelevant): https://github.com/ColinHebert/compose-404
It may sound a bit convoluted but here is what's happening:
 - docker-compose.yaml starts two containers, the first one is dind (the one we're going to test against through http). It uses privileges to run docker properly.
 - The second container runs a docker container "client" which is an ubuntu box with docker-compose installed. The client container is linked to dind container and has the env variable `DOCKER_HOST=docker:2375` (meaning that docker commands run inside this container are going straight to dind
 - When starting the client container, we attempt to run docker-compose which ends up failing on the 404.

I'm not 100% across the reason why the HTTP 404 bubbles up in my case. When running against a socket (albeit a different environment), the 404 gets caught properly ending with:

```pip._vendor.requests.packages.urllib3.connectionpool._make_request: "GET /v1.25/networks/mytest_default HTTP/1.1" 404 50```

### PR DESCRIPTION
**Pull request by shin-**
Fixes #4425 
Fixes #4483

### CODE REVIEW

**Comment by shin-** [comment]
#4421
