### ISSUE TITLE
[1.6.0rc2] ImportError: cannot import name create_ipam_config

### ISSUE THREAD

**Issue by wil93** [docker/compose#2792]
I'm getting this error whenever I run any docker-compose command, after upgrading to 1.6.0rc2

```
Traceback (most recent call last):
  File "/home/ioi/.local/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.6.0rc2', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/home/ioi/.local/lib/python2.7/site-packages/compose/cli/main.py", line 25, in <module>
    from ..project import NoSuchService
  File "/home/ioi/.local/lib/python2.7/site-packages/compose/project.py", line 21, in <module>
    from .network import Network
  File "/home/ioi/.local/lib/python2.7/site-packages/compose/network.py", line 7, in <module>
    from docker.utils import create_ipam_config
ImportError: cannot import name create_ipam_config
```

**Comment by dnephin** [comment]
Ah, I assume you've used `pip` to install. Our `requirements.txt` is still wrong. Compose requires `docker-py >= 1.7.0rc3`

**Comment by wil93** [comment]
Yes I  used pip

**Comment by s7v7nislands** [comment]
pip install -U docker-py==1.7.0rc3

fixed after update docker-py

**Comment by aanand** [comment]
Compose 1.6.0 is out. `pip install docker-compose==1.6.0` should fix this.
