### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'tobuf'

### ISSUE THREAD

**Issue by rishimathur81** [docker/compose#4363]
I upgraded to the latest docker version (1.13) for mac os x and when I try to run docker-compose I get the following error:

Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 64, in main
  File "compose/cli/main.py", line 116, in perform_command
  File "compose/cli/main.py", line 848, in up
  File "compose/project.py", line 389, in up
  File "compose/service.py", line 302, in ensure_image_exists
  File "compose/service.py", line 786, in build
  File "site-packages/docker/api/build.py", line 139, in build
  File "site-packages/docker/utils/utils.py", line 105, in tar
  File "tarfile.py", line 2046, in addfile
AttributeError: 'NoneType' object has no attribute 'tobuf'

Everything was working fine on all previous versions of docker for osx until this recent upgrade

**Comment by remear** [comment]
I encountered this in my projects today. It turned out to be something compose didn't like in the`tmp/sockets` directory of my rails application. Adding it to my .dockerignore has resolved the issue so far.

**Comment by norbertpapp** [comment]
Got the same error message for any docker-compose command, just after the update. (centos image with nginx and php)

**Comment by adamfeuer** [comment]
I am also getting this error after updating to Docker for Mac 1.13.0.

**Comment by rishimathur81** [comment]
I had to downgrade to 1.12.5 to get it working again.

**Comment by matheusrocha89** [comment]
I have the same problem here. I will make a downgrade to make it work again. This happened to me after update to Docker for Mac 1.13.0 too

**Comment by atamahjoubfar** [comment]
I had the same issue for composing a Python project after upgrading to 1.13.0 on a Mac. It got resolved by cloning the project directory again.

**Comment by shin-** [comment]
Thanks for the report everyone.

For those who have encountered the bug, could you provide your OS (It seems like everyone here is on OSX?) as well as the output of `docker-compose version`?

Thanks again.

**Comment by remear** [comment]
```
Mac OS X El Capitan 10.11.6
docker-compose version 1.10.0, build 4bd6f1a
docker-py version: 2.0.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```

For my project, it seems to dislike the socket I have under `tmp/sockets`
```
ls -la tmp/sockets
total 0
drwxr-xr-x  4 me  staff  136 Dec 12 12:37 .
drwxr-xr-x  7 me  staff  238 Jan 23 08:15 ..
srwxrwxrwx  1 me  staff    0 Oct  3 09:40 server.sock
```

**Comment by rishimathur81** [comment]
OSX Sierra

docker-compose version 1.9.0, build 2585387
docker-py version: 1.10.6
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016

**Comment by adamfeuer** [comment]
```
MacOS 10.11.6
docker-compose version 1.10.0, build 4bd6f1a
docker-py version: 2.0.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```

**Comment by atamahjoubfar** [comment]
```Shell
macOS Sierra: version 10.12.2
docker-compose version 1.10.0, build 4bd6f1a
docker-py version: 2.0.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```

**Comment by atamahjoubfar** [comment]
The issue came back for me. It happens when `docker-compose up` is trying to rebuild an image. I get it when I try `docker-compose up --build` or `docker-compose build`. Any other solution instead of cloning again every time!

**Comment by shin-** [comment]
@atamahjoubfar Do you have any socket file in your build context? What does `find . -name '*.sock'` output? What about `find . -size -1c ! -name '__init__.py' ! -path './.git/*'` ?

**Comment by atamahjoubfar** [comment]
@shin- Yes, I do have a socket file in my build. Both of the outputs are the same socket file:
```shell
ata@macbook:~$ find . -type s
./socket/mysocket.sock
ata@macbook:~$ find . -name '*.sock'
./socket/mysocket.sock
```

**Comment by shin-** [comment]
@atamahjoubfar Add it to your `.dockerignore`, that should solve the issue for the time being.

**Comment by florent-babylon** [comment]
Had the same issue on OSX with Docker 1.13.0, `docker-compose version`:
```docker-compose version 1.10.0, build 4bd6f1a
docker-py version: 2.0.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016```

There was indeed a stray `stats.socket` file in the build directory; removing it fixed the issue. 👍

**Comment by rccrdpccl** [comment]
``
Linux 4.7.0-0.bpo.1-amd64 x86_64 GNU/Linux
docker-compose version 1.11.1, build 7c5d5e4
docker-py version: 2.0.2
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
``

There was also a socket in ``.ppm/run/controller.sock``, also in my case after removing it fixed the issue.

**Comment by shin-** [comment]
Thanks all, the issue was identified, a fix is in `docker-py`'s master branch https://github.com/docker/docker-py/pull/1408 and will be part of an upcoming release.
